repos:
  - repo: local
    hooks:
      - id: gdlint
        name: gdlint
        entry: gdlint
        language: python
        additional_dependencies: [gdtoolkit==4.3.3]       
        types: [gdscript]
        exclude: |
          (?x)^(
            addons/godot_uro/godot_uro.gd | 
            addons/godot_uro/godot_uro_api.gd |
            addons/godot_uro/godot_uro_requester.gd |
            addons/Godot-MToon-Shader/.* |
            addons/actor/.* |
            addons/background_loader/.* |
            addons/canvas_plane/.* |
            addons/emote_theme/.* |
            addons/entity_manager/.* |
            addons/extended_kinematic_body/.* |
            addons/fade_manager/.* |
            addons/flat_viewport/.* |
            addons/gd_util/.* |
            addons/godot-xr-tools/.* |
            addons/godot_speech/.* |
            addons/godot_state_charts/.* |
            addons/input_manager/.* |
            addons/kenney_ui_audio/.* |
            addons/line_renderer/.* |
            addons/math_util/.* |
            addons/navigation_controller/.* |
            addons/network_manager/.* |
            addons/sar1_mocap_manager/.* |
            addons/sar1_screenshot_manager/.* |
            addons/sar1_vr_manager/.* |
            addons/smoothing/.* |
            addons/spatial_game_viewport_manager/.* |
            addons/state_machine/.* |
            addons/textureRectUrl/.* |
            addons/vrm/.* |
            addons/vsk_avatar/.* |
            addons/vsk_editor/.* |
            addons/vsk_entities/.* |
            addons/vsk_importer_exporter/.* |
            addons/vsk_manager/.* |
            addons/vsk_map/.* |
            addons/vsk_menu/.* |
            addons/vsk_version/.* |
            addons/vsk_vrm_avatar_tool/.* |
            addons/xr_vignette/.* 
            )$

      # VRM and godot_state_charts are ignored because upstream changes are complicated
      - id: gdformat
        name: gdformat
        entry: gdformat
        language: python
        additional_dependencies: [gdtoolkit==4.3.3]
        types: [gdscript]
        exclude: |
          (?x)^(
            addons/godot_state_charts/.* |
            addons/vrm/.* |
            addons/Godot-MToon-Shader/.* 
          )$
