repos:
  - repo: local
    hooks:
      - id: gdlint
        name: gdlint
        entry: gdlint
        language: python
        additional_dependencies: [gdtoolkit==4.3.3]       
        files: ^addons/godot_uro/(godot_uro_helper|http_pool)\.gd$
        types: [gdscript]

      # VRM and godot_state_charts are ignored because upstream changes are complicated
      - id: gdformat
        name: gdformat
        entry: gdformat
        language: python
        additional_dependencies: [gdtoolkit==4.3.3]
        types: [gdscript]
        exclude: |
          (?x)^(
            addons/godot_state_charts/.* |
            addons/vrm/.* |
            addons/Godot-MToon-Shader/.* 
          )$
